<?php

namespace App\Election\Printing\Documents;

use Carbon\CarbonImmutable;
use RuntimeException;
use Symfony\Component\Process\ExecutableFinder;
use Symfony\Component\Process\Process;

/**
 * Renders the voter control-number receipt as a PDF.
 *
 * This is generated by shelling out to Ghostscript (PostScript -> PDF)
 * rather than hand-serializing raw PDF objects. A prior hand-rolled
 * implementation produced PDFs that displayed correctly in ordinary
 * viewers and even rasterized correctly under Ghostscript's own PDF
 * interpreter, but reproducibly printed garbled through the CUPS filter
 * chain used for thermal (zj80) queues, even after adding complete
 * /Widths and /FontDescriptor entries. Generating the document through
 * Ghostscript itself (already a first-class dependency of this app, see
 * GhostscriptPdfTextExtractor) produces a fully standard PDF and was
 * confirmed to print correctly with identical visual content.
 */
final class ControlNumberReceiptPdf
{
    /**
     * The production printer's actual paper stock is a 2.25 inch
     * (~57 mm) roll, not the 80 mm roll the "Thermal80" CUPS queue name
     * and zj80 driver assume. Content wider than the physical paper is
     * simply cut off by the printer (there is no paper to print on past
     * its edge) - this was confirmed directly on the device: cropping
     * persisted at both 80 mm and ~70 mm page widths and only stopped
     * once the page width was reduced to fit the actual paper.
     *
     * Use the same 48 mm printable width proven reliable on the
     * previous 58 mm-class thermal printer this device used
     * (2.25 in / ~57 mm roll is effectively the same paper class as a
     * nominal 58 mm roll), leaving a small margin on each side of the
     * physical roll.
     */
    private const PageWidth = 136.06;

    private const PageHeight = 180;

    /**
     * @param  array<string, mixed>  $release
     * @param  array<string, mixed>  $configuration
     */
    public function render(array $release, array $configuration): string
    {
        $controlNumber = (string) ($release['release_code'] ?? '');
        $fontSize = $this->fontSize($controlNumber);
        $x = (self::PageWidth - $this->textWidth($controlNumber, $fontSize)) / 2;
        $y = ((self::PageHeight - $fontSize) / 2) + 11;
        [$precinctLine, $timeLine] = $this->finePrint($release, $configuration);
        $finePrintSize = 5.8;
        $precinctLineX = (self::PageWidth - $this->textWidth($precinctLine, $finePrintSize, false)) / 2;
        $timeLineX = (self::PageWidth - $this->textWidth($timeLine, $finePrintSize, false)) / 2;

        // Two rotation directions were tried (90 and -90 with matching
        // translate) attempting to compensate for what looked like
        // driver auto-rotation. Neither was confirmed correct on the
        // physical device, and the added transform caused the fine
        // print lines to disappear entirely. The operator has opted to
        // accept whatever orientation the printer naturally produces
        // rather than keep fighting it, so declare the page directly at
        // the corrected printable width/height with no added rotation.
        $postscript = sprintf(
            "%%!PS\n<< /PageSize [%.2F %.2F] >> setpagedevice\n".
            "0.05 0.05 0.05 setrgbcolor\n/Courier-Bold findfont %.2F scalefont setfont\n%.2F %.2F moveto\n(%s) show\n".
            "0.42 0.42 0.42 setrgbcolor\n/Helvetica findfont %.2F scalefont setfont\n%.2F 22.00 moveto\n(%s) show\n%.2F 13.00 moveto\n(%s) show\n".
            "showpage\n",
            self::PageWidth,
            self::PageHeight,
            $fontSize,
            max(0, $x),
            $y,
            $this->encode($controlNumber),
            $finePrintSize,
            max(6, $precinctLineX),
            $this->encode($precinctLine),
            max(6, $timeLineX),
            $this->encode($timeLine),
        );

        return $this->convertToPdf($postscript);
    }

    private function convertToPdf(string $postscript): string
    {
        $configuredBinary = (string) config('election.pdf.ghostscript_binary', 'gs');
        $binary = $this->resolveBinary($configuredBinary);
        $base = sys_get_temp_dir().'/aes-control-number-'.bin2hex(random_bytes(8));
        $inputPath = $base.'.ps';
        $outputPath = $base.'.pdf';

        try {
            file_put_contents($inputPath, $postscript);

            $process = new Process([
                $binary,
                '-q',
                '-dNOPAUSE',
                '-dBATCH',
                '-dSAFER',
                '-sDEVICE=pdfwrite',
                '-o',
                $outputPath,
                $inputPath,
            ]);
            $process->setTimeout(30);
            $process->run();

            $pdf = is_file($outputPath) ? (file_get_contents($outputPath) ?: '') : '';

            if (! $process->isSuccessful() || $pdf === '') {
                throw new RuntimeException("Unable to render control number receipt with Ghostscript [{$configuredBinary}]: ".$process->getErrorOutput());
            }

            return $pdf;
        } finally {
            @unlink($inputPath);
            @unlink($outputPath);
        }
    }

    private function resolveBinary(string $configuredBinary): string
    {
        if (str_contains($configuredBinary, DIRECTORY_SEPARATOR)) {
            return $configuredBinary;
        }

        return (new ExecutableFinder)->find(
            $configuredBinary,
            $configuredBinary,
            [
                dirname(PHP_BINARY),
                '/opt/homebrew/bin',
                '/usr/local/bin',
                '/usr/bin',
            ],
        );
    }

    private function fontSize(string $controlNumber): float
    {
        $digits = max(1, strlen($controlNumber));

        return min(84, (self::PageWidth - 24) / ($digits * 0.60));
    }

    private function textWidth(string $text, float $size, bool $monospace = true): float
    {
        return strlen($text) * $size * ($monospace ? 0.60 : 0.49);
    }

    /**
     * @param  array<string, mixed>  $release
     * @param  array<string, mixed>  $configuration
     * @return array{0: string, 1: string}
     */
    private function finePrint(array $release, array $configuration): array
    {
        $precinctId = (string) ($configuration['precinct_id'] ?? 'unknown');
        $cityMunicipality = (string) ($configuration['city_municipality'] ?? $configuration['location']['city_municipality'] ?? 'unknown');
        $timestamp = (string) ($release['printed_at'] ?? $release['created_at'] ?? $release['expires_at'] ?? now()->toIso8601String());
        $printedAt = CarbonImmutable::parse($timestamp)
            ->setTimezone(date_default_timezone_get())
            ->format('d Hi\H M Y');

        return ["Precinct {$precinctId} | {$cityMunicipality}", $printedAt];
    }

    private function encode(string $value): string
    {
        $normalized = str_replace(["\r", "\n"], ' ', $value);
        $ascii = iconv('UTF-8', 'ASCII//TRANSLIT', $normalized) ?: $normalized;

        return str_replace(['\\', '(', ')'], ['\\\\', '\\(', '\\)'], $ascii);
    }
}
